### ISSUE TITLE
non-passthrough of double quotes

### ISSUE THREAD

**Issue by mirabilos** [fruux/sabre-vobject#129]
Hi,

parsing an iCalendar file then serialising it gives me a diff. Among other things, double-quotes are now prefixed with a backslash because the incoming “\"” is handled as backslash plus double-quote, instead of escaped double-quote (which is what KDE Kontact wrote):

```
-DESCRIPTION:innerer•text\ngeht yber\n\nmehrere•zeilen\n\nab dem 
- 10.09. 6x jede woche bis auf 17.09. also noch 24.09. und 01.10. und 
- 08.10. und 15.10.\n\nescaping: ' \" \\ \; \, : & < > !\n\nund mit 
- modifikation.
+DESCRIPTION:innerer•text\ngeht yber\n\nmehrere•zeilen\n\nab dem 10.09. 
+ 6x jede woche bis auf 17.09. also noch 24.09. und 01.10. und 08.10. und 15
+ .10.\n\nescaping: ' \\" \\ \; \, : & < > !\n\nund mit modifikation.
```

**Comment by evert** [comment]
Closing this, for motivation, read the thread from #132
