### ISSUE TITLE
Floating icalendar dates are not correctly roundtripped

### ISSUE THREAD

**Issue by kewisch** [fruux/sabre-vobject#179]
When parsing an iCalendar string that contains a local/floating time, the json switches the timezone to UTC. Example:

```php
$ical = "BEGIN:VCALENDAR
BEGIN:VEVENT
UID:a03a61fc-ef74-413a-84b9-adecc317719b
SUMMARY:test
DTSTART:20150108T150000
DTEND:20150108T160000
END:VEVENT
END:VCALENDAR";

print $ical . "\n";
$x = \Sabre\VObject\Reader::read($ical);
print json_encode($x->jsonSerialize());
```
The result contains this:

```json
["dtstart",{},"date-time","2015-01-08T15:00:00Z"],
["dtend",{},"date-time","2015-01-08T16:00:00Z"]
```

I would expect this:

```json
["dtstart",{},"date-time","2015-01-08T15:00:00"],
["dtend",{},"date-time","2015-01-08T16:00:00"]
```

**Comment by Hywan** [comment]
Hello :-),

Thank for the report, but why? Is it part of the spec'?

**Comment by kewisch** [comment]
Check out http://tools.ietf.org/html/rfc5545#section-3.3.5, specifically FORM 1: DATE WITH LOCAL TIME

**Comment by Hywan** [comment]
I will work on this bug tomorrow. @evert, because we have a different timezone, feel free to work on this bug for your today if you have time. I am not blocking this bug for me.

**Comment by evert** [comment]
k =) will probably take a look today then.

**Comment by Hywan** [comment]
@evert Only if you have time ;-).

**Comment by kewisch** [comment]
Thanks for diving this so quickly. I've tracked it down to DateTimeParser setting UTC if $tz is null, which it is for floating times. Removing that check makes the example above work, but will likely break other things. Also, I believe PHP assumes the local timezone if $tz = null.

**Comment by kewisch** [comment]
Another bit of information: when I remove the is_null check the example does seem to work, but it didn't work when retrieving an event via the sabredav server I am running. This ended up happening because the server uses `date_default_timezone_set('UTC')`
