### ISSUE TITLE
Tests for the JSON reader are missing

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-vobject#183]

**Comment by evert** [comment]
Are you looking for this:

https://github.com/fruux/sabre-vobject/blob/3.3/tests/VObject/Parser/JsonTest.php

**Comment by Hywan** [comment]
Partly yes. Why is it not in the `ReaderTest.php` file?

**Comment by evert** [comment]
Legacy.. The Mimedir parser was 100% in Reader.php at first, but then moved to a separate class. I originally intended to deprecate Reader.php, but it's kinda handy to have a quick way to parse something.

Really the mimedir tests should move to Parser\MimeDirTest.php, but it didn't seem that important at the time.

**Comment by Hywan** [comment]
@evert Ok ;-).
