### ISSUE TITLE
Create all-day event

### ISSUE THREAD

**Issue by bezruki** [fruux/sabre-vobject#184]
In the version 2 there was a way to create a DATE only 'vevents' - but that doesn't work in v3. When using the PHP DateTime objects, the VEVENT always has a time. I can't figure out how to override this.

**Comment by evert** [comment]
You can specify the date as a string, instead of a PHP DateTime object.

**Comment by bezruki** [comment]
Hi evert - thanks for quick reply. I've tried that but still getting a .ics file that is formatted like so:
`DTSTART:20130407` - which is not recognized as an all-day event by calendar clients. The correct format appears to be:
`DTSTART;VALUE=DATE:20130407` - I think semi-colon right after DTSTART is what triggers it.

Is there a format for a string I need to use for the date? I've tried a few different things without any luck.

**Comment by evert** [comment]
Ok, so the current behavior is that you need to actually do this:

```php
<?php

namespace Sabre\VObject;

include 'vendor/autoload.php';
$vcal = new Component\VCalendar();
$vevent = $vcal->add('VEVENT');

$dtstart = $vcal->add('DTSTART','20150117');
$dtstart['VALUE'] = 'DATE';

echo $vcal->serialize();
```

This works. You can even pass a PHP DateTime object, and setting the value to `DATE` will automatically correct the format.

This is actually the only property that does this 'live conversion' as it's such a common occurrence.

Let me know if this works for you.

**Comment by mattleff** [comment]
Just for the record (anyone else running across this), in the example @evert gave above, it should be as follows:

```php
<?php

namespace Sabre\VObject;

include 'vendor/autoload.php';
$vcal = new Component\VCalendar();
$vevent = $vcal->add('VEVENT');

$dtstart = $vevent->add('DTSTART','20150117');
$dtstart['VALUE'] = 'DATE';

echo $vcal->serialize();
```

`$vevent->add('DTSTART','20150117');` instead of `$vcal->add('DTSTART','20150117');`

**Comment by evert** [comment]
Whoops! So close

**Comment by bezruki** [comment]
Sorry for the late reply - tried it and it worked like magic! Thank you, guys.
