### ISSUE TITLE
jCal does not support `time` property type

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-vobject#185]
Try the following code:
```php
VObject\Reader::readJson('["vcalendar", ["foo", {}, "time", "12:00:00"]]');
```
It should fail.

I can fix this in the following days.

**Comment by evert** [comment]
Why should it fail? it looks ok to me :)

**Comment by armin-hackmann** [comment]
just comparing to the data we use in our webapp, it should be:
```php
VObject\Reader::readJson('["vcalendar", [["foo", {}, "time", "12:00:00"]]]');
```
With an additional Property:
```php
VObject\Reader::readJson('["vcalendar", [["foo", {}, "time", "12:00:00"], ["bar", {}, "time", "13:00:00"]]]');
```

**Comment by evert** [comment]
Right.. it's missing that extra bracket.

**Comment by evert** [comment]
But I doubt the missing brackets is what @Hywan was talking about, no?

**Comment by Hywan** [comment]
@evert Humm, in fact, @armin-hackmann is right and I feel dumb on this one :-D. Consider I was tired. This is the official story.

**Comment by Hywan** [comment]
Well, the initial bug I was trying to detect is here though.
```php
        $component = VObject\Reader::readJson('["vcalendar", [["foo", {}, "time", "12:00:00"]]]');
        $this->assertEquals(
            'BEGIN:VCALENDAR' . CRLF .
            'FOO;VALUE=TIME:120000' . CRLF .
            'END:VCALENDAR' . CRLF,
            VObject\Writer::write($component)
        );
```
We have `FOO;VALUE=TIME:12:00:00` instead of `FOO;VALUE=TIME:120000`.
I can fix this bug I think. I encounter the same bug with xCal. There is no test for the `time` property type with jCal so far.

**Comment by evert** [comment]
That makes sense.. so basically the time property needs a new `getJsonValue()` / `setJsonValue()`

**Comment by Hywan** [comment]
@evert Exact! I can do that but after my xCal patch… or I can start a new branch. I will give it a shot today.

**Comment by evert** [comment]
I'm assuming this didn't happen yet, so I'll add a fix to the 3.3 branch as well for this :)

**Comment by evert** [comment]
Ok .. there's more going on here :) The property actually has a bunch of 'json' behavior. Specifically, it has the 'getJsonValue' fully implemented for vCards (not iCalendar).

I suspect that the time property in vCards is different than iCalendar. I also suspect that the extra colons are 100% legal in vCard, but probably not in iCalendar!

So what needs to happen is that we need to move this Time property from `Sabre\VObject\Property\Time` to `Sabre\VObject\Property\VCard\Time` and create a new `Sabre\VObject\Property\ICalendar\Time`, _if_ what I'm saying is actually correct.

**Comment by Hywan** [comment]
@evert Will check Monday :-). Difficult weekend here :-p.
