### ISSUE TITLE
jCal and jCard UTC-OFFSET is not well formatted

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-vobject#186]
According to http://tools.ietf.org/html/rfc5545#section-3.6.5, UTC-OFFSET must be formatted `+0500` and not `+05:00`.

**Comment by Hywan** [comment]
I know the fix belongs to a PR about xCal but it is a little bit hard to extract the patch from it (becase it updates a previous patch related to xCal etc.).

**Comment by evert** [comment]
:+1:
