### ISSUE TITLE
LAST-MODIFICATION vs LAST-MODIFIED

### ISSUE THREAD

**Issue by gkertai** [fruux/sabre-vobject#187]
The `getValidationRules()` methods in the `VEvent`, `VJournal`, `VTimeZone`, and `VTodo` classes define a property name `LAST-MODIFICATION`, while [RFC5545] (http://tools.ietf.org/html/rfc5545#section-3.8.7.3) defines it as `LAST-MODIFIED`.

Could this be a typo, or a purposeful distinction?

**Comment by evert** [comment]
Definitely a typo

**Comment by Hywan** [comment]
:+1:
