### ISSUE TITLE
Update PHP version requirement in composer.json

### ISSUE THREAD

**Issue by rickdenhaan** [fruux/sabre-vobject#194]
The composer.json file currently indicates a PHP version requirement of ">=5.3.1", which is incorrect as in some places short array syntax is used which is only supported in PHP 5.4 and later.

Version 2.1 does not use short array syntax and is perfectly valid 5.3.* code, but the 3.* version should require PHP 5.4+.

**Comment by evert** [comment]
Hi Rick,

We have a near >90% unittest code coverage, and every single commit gets tested in PHP 5.3, 5.4, 5.5, 5.6 and hhvm, as you can see here:

https://travis-ci.org/fruux/sabre-vobject/builds/47838234

I often mess up the array syntax, but travis immediately notifies me, and we haven't had a single release that was broke in that regard.

The master branch however, depends on PHP 5.5, but that will in the future become vobject 4.0 and is currently unreleased.

So if you're seeing something I'm not seeing, let me know :)

**Comment by rickdenhaan** [comment]
Hi Evert,

The problem isn't as bad as I thought :)

There are two files in the bin folder with short array syntax: `fetch_windows_zones.php` and `generate_vcards`. In my particular case, I'm using the PHP 5.3 ionCube Encoder for my entire project, which broke when trying to encrypt `fetch_windows_zones.php`.

I've just issued a pull request to fix it: https://github.com/fruux/sabre-vobject/pull/195

**Comment by evert** [comment]
If you distribute a binary version of vobject, just make sure you include the LICENSE file in plain text =)

**Comment by rickdenhaan** [comment]
I just checked to be sure: ionCube doesn't encrypt the license file ;)

**Comment by evert** [comment]
cool =)
