### ISSUE TITLE
Optimizing accessing specific children in components

### ISSUE THREAD

**Issue by evert** [fruux/sabre-vobject#197]
This is slow:

```php
echo $vcalendar->VEVENT->UID;
```

Because the vcalendar will traverse all its children to find the VEVENT, and the VEVENT will traverse all its children to find the UID.

We can optimize this quite a bit, but one thing that's standing in our way, is that the `$children` property is public.

For 4.0 we should remove that, and instead move to a system that automatically indexes properties and sub-components by their name.

This became extremely obvious when profiling #196, but everything else that access properties by name would be affected by this.

**Comment by Hywan** [comment]
But you can have several `VEVENT` in the same `VCALENDAR` nop? So we could write `$vcalendar->VEVENT[1]->UID` nop?

**Comment by evert** [comment]
Yes, but the way that's implemented, is that it would still do a full scan of all properties in `VCALENDAR`.
