### ISSUE TITLE
Clean DateTimeParser

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-vobject#199]
We have too much DateTimeParser methods for vCard date, time, date-time and date-and-or-time formats. #192 recently introduce a new parser for the date-and-or-time format. We can split this parser in 3 parts: date, time and date-time respectively, and update the code using the old parsers. I am pretty sure they include bugs. Also, the new parser is well-tested.

Thoughts?

**Comment by evert** [comment]
There is definitely some duplication in the DateTimeParser, but I'm also not terribly worried about it. All of the code has unittests, so perhaps when we actually need to make modifications there it would be a better time to refactor this.

Perhaps at one point in the future we can unify all these parsers, as there's actually quite a bit of overlap. But yea, it looks good enough to me right now.
