### ISSUE TITLE
TZ Asia/Srednekolymsk does not exist in PHP5.3

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-vobject#203]
Yup, and it makes my tests fail ;-).
We have to:
  * [ ] cherry-pick https://github.com/fruux/sabre-vobject/commit/022ee3106bfec487e2691e7f3e0df86c2390ce00 from 3.3 to `master` and then
  * [ ] delete `Asia/Srednekolymsk` from 3.3.

**Comment by evert** [comment]
We should make those tests skippable.

**Comment by Hywan** [comment]
Perfect, thanks!
