### ISSUE TITLE
Recurrent all-day event with exceptions generates wrong RECURRENCE-ID

### ISSUE THREAD

**Issue by adobo** [fruux/sabre-vobject#213]
I am trying to expand a recurrent all-day (`VALUE=DATE`) event under VObject 3.4.2. Everything works as expected as long as it has no recurrence exceptions.

However, if I add a recurrence exception to the event and try to expand it again, I get a DATE-TIME formatted RECURRENCE-ID for that instance.

The following code shows the issue:

```php
$ics = <<<EVENT
BEGIN:VCALENDAR
PRODID:-//Sabre//Sabre VObject 3.3.5//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:a0bdd615-571d-4158-a6b7-06fcafc46965
SUMMARY:Sample event
RRULE:FREQ=WEEKLY
DTSTART;VALUE=DATE:20150302
DTEND;VALUE=DATE:20150303
END:VEVENT
BEGIN:VEVENT
UID:a0bdd615-571d-4158-a6b7-06fcafc46965
RECURRENCE-ID:20150309
SUMMARY:Sample event
DTSTART;VALUE=DATE:20150312
DTEND;VALUE=DATE:20150313
END:VEVENT
END:VCALENDAR
EVENT;

$vcalendar = \Sabre\VObject\Reader::read($ics);
$vcalendar->expand(
    new \DateTime('2015-03-01'),
    new \DateTime('2015-04-01')
);

foreach ($vcalendar->select('VEVENT') as $vevent) {
    echo "RECURRENCE-ID: " . $vevent->{'RECURRENCE-ID'} . "\n";
}
```

Expected output:

```
RECURRENCE-ID: 
RECURRENCE-ID: 20150309
RECURRENCE-ID: 20150316
RECURRENCE-ID: 20150323
RECURRENCE-ID: 20150330
```

Actual output:

```
RECURRENCE-ID: 
RECURRENCE-ID: 20150309T000000Z
RECURRENCE-ID: 20150316
RECURRENCE-ID: 20150323
RECURRENCE-ID: 20150330
```

**Comment by evert** [comment]
Hi!

I think it may have to do with the lack of `VALUE=DATE` on the `RECURRENCE-ID` property. So it might be a case of 'garbage in, garbage out'.

From rfc5545

> Value Type:  The default value type is DATE-TIME.  The value type can
> be set to a DATE value type.
>
> https://tools.ietf.org/html/rfc5545#section-3.8.4.4

What I gather from this is that the VALUE property would be required here.

**Comment by adobo** [comment]
You're right, I totally missed the `VALUE` parameter on the `RECURRENCE-ID`. VObject adds it when expanding, but I was simple not reading it.

Thank you for the clarification!
