### ISSUE TITLE
VCard\Date incorrectly serialized when initialized with DateTime object

### ISSUE THREAD

**Issue by thomascube** [fruux/sabre-vobject#217]
Consider the following test case:
```php
$datetime = new \DateTime('2014-04-02');
$vcard = new VObject\Component\VCard();
$prop = $vcard->createProperty('BDAY', $datetime, null, 'DATE');
echo $prop->serialize();
````
Results in
```
BDAY:20140402T000000Z
```
instead of the expected
```
BDAY;VALUE=DATE:2014-04-02
```

**Comment by thomascube** [comment]
PR will follow soon...

**Comment by thomascube** [comment]
Sorry, the correct result would be either
 `BDAY:20140402` according to RFC 6350
or
 `BDAY:2014-04-02` according to RFC 2426.

**Comment by evert** [comment]
They are actually both valid. I forget which we prefer. I would personally prefer whatever 'most people' are doing, but not sure which one of those it is.

**Comment by evert** [comment]
Go for the format with dashes =)

**Comment by thomascube** [comment]
The DateAndOrTime class uses Ymd\\THis for date formatting, that's RFC 6350 as far as I can tell.

**Comment by evert** [comment]
Hm yes it does say that the extended format is now allowed. Sounds good then!
