### ISSUE TITLE
Needs better support for DateTime lists

### ISSUE THREAD

**Issue by georgehrke** [fruux/sabre-vobject#219]
I have a calendar file with different recurring events with exceptions.
There are 3 different EXDATEs:

1. No value: `EXDATE;TZID=Europe/Berlin:` <br />
2. 2 values: `EXDATE;TZID=Europe/Berlin:20150514T110000,20150528T110000` <br />
3. 2 values with comma at the end `EXDATE;TZID=Europe/Berlin:20150514T130000,20150528T130000,` 

_Expected behavior_: Sabre VObject handles all three EXDATEs correctly.
_Actual behavior_: Sabre VObject fails to handle EXDATEs correctly. (for exact output see gist) <br>

Broken example code: https://gist.github.com/georgehrke/c27be5982d8dd367cbdb

- Sabre-Version: __3.3__
- PHP-Version: __5.6.7__

---

DateTimeParser::parseDateTime() doesn't seem to expect a list of DateTimes, but rather a single DateTime.
Nevertheless Property\ICalendar\DateTime::validate hands over a list of DateTimes.
(see https://github.com/fruux/sabre-vobject/blob/3.3.5/lib/Property/ICalendar/DateTime.php#L375)

**Comment by georgehrke** [comment]
Note: 
The `EXDATE;TZID=Europe/Berlin:20150514T110000,20150528T110000` issue applies only to `validate()`.

The other 2 issues also trigger failure in `jsonSerialize()`.
https://github.com/fruux/sabre-vobject/blob/3.4/lib/Property/ICalendar/DateTime.php#L172
It tries to parse $part even if part is an empty string.

If we would add a check like this: ...
```php
foreach($this->getParts() as $part) {
    if (trim($part) === '') {
         continue;
    }
    $dts[] = DateTimeParser::parse($part, $timeZone);
}
```
..., it would only solve the issue with `EXDATE;TZID=Europe/Berlin:20150514T130000,20150528T130000,`.

`EXDATE;TZID=Europe/Berlin:` would still cause issues, as $dts would be empty and some other parts like https://github.com/fruux/sabre-vobject/blob/3.4/lib/Property/ICalendar/DateTime.php#L279 expect this array to have at least one element (which is supposed to be an instance of DateTime).

**Comment by evert** [comment]
Hi @georgehrke ,

I am actually not certain whether these two should be supported:

> No value: EXDATE;TZID=Europe/Berlin:
> 2 values with comma at the end EXDATE;TZID=Europe/Berlin:20150514T130000,20150528T130000,

The specification says that EXDATE is defined as:

    exdate     = "EXDATE" exdtparam ":" exdtval *("," exdtval) CRLF
    exdtval    = date-time / date
    
This definitely leaves to room for empty values, from a specification point of view.

However, the validation issue I agree with and I will address this.

**Comment by evert** [comment]
Just committed 74a6e0e, which should address your issue. Let me know if this is sufficient to close this ticket.

**Comment by georgehrke** [comment]
> Just committed 74a6e0e, which should address your issue.

Thanks for fixing the validator issue. :)

> Let me know if this is sufficient to close this ticket.

I can see your point that you don't want to support broken icals, but there is actually software out there generating this (actually my university's schedule tool). So I would be happy if you could add a fix. If you decide against adding a fix, I'd appreciate if sabre/dav would already throw an ParseException when reading such events.

**Comment by evert** [comment]
One issue I have with making the parser more strict, is that it may start tripping over iCalendar objects that exist 'in the wild', exactly like your use-case.

That's sort of why there's a 'general parser' that's fairly loose and will parse iCalendar as long as it mostly adheres to the general structure, and a separate validator that does look at the data strictly.

I think making everything more strict during the parsing phase, and effectively call validate() and do hard failures when parsing objects will make a lot of people unhappy.

However, I am thinking of adding a 'strict mode' in sabre/dav in the next version that does automatically call validate() on every incoming object, and in the next-next version turn it that setting on by default.

So the current 'don't fail on parse' and 'error on validate' is consistent with how the rest works.

Thoughts?
