### ISSUE TITLE
Add ability to limit the amount of recurrences, for DDOS prevention.

### ISSUE THREAD

**Issue by stringerbell** [fruux/sabre-vobject#220]
I'd love to see a way to pass options (or have the default be set unless explicitly set otherwise) for removing support for the `RRULE:FREQ` of:
- `SECONDLY`
- `MINUTELY`
- `HOURLY`

or in other words, pick which frequencies you'd like to support when expanding.

The use case would be times that you want to make sure to not generate a hojillion events on a calendar that looks something like this when calling `expand()`:

```
BEGIN:VCALENDAR
METHOD:PUBLISH
VERSION:2.0
X-WR-CALNAME:RECUR!
PRODID:-//Apple Inc.//Mac OS X 10.9.5//EN
X-APPLE-CALENDAR-COLOR:#E6C800
X-WR-TIMEZONE:America/Los_Angeles
CALSCALE:GREGORIAN
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
DTSTART:20070311T020000
TZNAME:PDT
TZOFFSETTO:-0700
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
DTSTART:20071104T020000
TZNAME:PST
TZOFFSETTO:-0800
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20150408T174949Z
UID:78B1FFA6-85C4-418B-8C47-EC0664A203B2
RRULE:FREQ=SECONDLY;INTERVAL=1
DTEND;TZID=America/Los_Angeles:20150406T124500
TRANSP:OPAQUE
SUMMARY:!RECUR!
DTSTART;TZID=America/Los_Angeles:20150406T114500
DTSTAMP:20150408T175001Z
SEQUENCE:3
END:VEVENT
END:VCALENDAR
```

Although this isn't likely that this would be a real feed, it'd be nice to guarantee that the `RRuleIterator`  wouldn't even attempt to parse it, and throw an InvalidArgumentException.

Also, many thanks for making the library. It's awesome. :)

**Comment by evert** [comment]
Well, right now we don't support `SECONDLY` and `MINUTELY`, so that solves a big part of that problem.

Instead of allowing certain types of rules to be disabled though, the plan is to simply allow people to configure how many instances might at most be generated. I feel that this is a solution that's a bit more fine-grained and flexible, but also a lot easier to do.

**Comment by stringerbell** [comment]
That's a great idea, and would probably address my use case.

Thanks!
