### ISSUE TITLE
workaround for bug 880 in owncloud contacts app 

### ISSUE THREAD

**Issue by babelouest** [fruux/sabre-vobject#225]
as mentioned in https://github.com/owncloud/contacts/issues/880 , there is a problem in some owncloud contacts import when creating a `X-SERVICE-TYPE` property. This property is created as a string type, not a Property object. This leads to issues when importing some data.

A workaround has been created here: https://github.com/owncloud/3rdparty/pull/172 , I've been asked to bring it upstream.

**Comment by evert** [comment]
See https://github.com/owncloud/contacts/issues/880
