### ISSUE TITLE
At sync, Apple Calendar refuses changed URL from "URL;VALUE=URI:" syntax

### ISSUE THREAD

**Issue by ronanguilloux** [fruux/sabre-vobject#227]
Hi there,

connecting a SavreDAV instance having Sabre's vObject `3.4.2` with Apple Calendar client `v7.0` (build `1841.1` on OSX `10.9.5`), I have issues with events generated in Apple Calendar client:

Manually creating an event in Apple Calendar,
here is the iCal that is actually sent by Apple Calendar to SabreDAV: 

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.9.5//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20150519T130116Z
UID:661FF39B-FDC2-4FF7-871A-0C80501D2D23
DTEND;VALUE=DATE:20150521
TRANSP:TRANSPARENT
SUMMARY:gqeger
DTSTART;VALUE=DATE:20150520
DTSTAMP:20150519T131019Z
SEQUENCE:3
URL;VALUE=URI:projet-ode.fr/event/95%231    <-- note the URL;VALUE... format from Apple
END:VEVENT
END:VCALENDAR
```

SabreDAV custom-persits it in ElasticSearch (PR to come!) with a jCal format (using vObject to generate such JSON). There is no data loss: all is OK at this point.

Then, as expected, SavreDAV send back a response: here is the iCal received by Apple Calendar from SavreDAV:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.9.5//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20150519T130116Z
UID:661FF39B-FDC2-4FF7-871A-0C80501D2D23
DTEND;VALUE=DATE:20150521
TRANSP:TRANSPARENT
SUMMARY:gqeger
DTSTART;VALUE=DATE:20150520
DTSTAMP:20150519T131019Z
SEQUENCE:3
URL:projet-ode.fr/event/95%231     <-- note the new URL:... syntax format changed by vObject
END:VEVENT
END:VCALENDAR
```

__The issue is__: Apple Calendar refuses to accept that callback: Apple CalendarAgent throws a CalDAVWriteEntityQueueableOperation error.

Only the `URL` field as changed, but for Apple Calendar, such sync attempt fails.

We (@ErrOrnAmE & I) suppose that just because of this URL field syntax change, Apple does not accept the end the sync operation with success.

A __workaround__ is to change line 168 in `Sabre\VObject\Parser\Json.php` file, as follow: 

```php
if ($defaultPropertyClass !== get_class($prop) || $defaultPropertyClass == "Sabre\VObject\Property\Uri") {
```

and change an expected VEvent file content inside the `testRoundTripJCal` method in the related `JsonTest.php` unit test file (line 333), to make unit tests work again.

To you, 

- is this an Apple-specific behavior you wan vObject to address? 
- If yes, does this worth a PR?

Thanks!

**Comment by evert** [comment]
Hi!

This line:

    URL;VALUE=URI:projet-ode.fr/event/95%231    <-- note the URL;VALUE... format from Apple

is actually equivalent to:

    URL:projet-ode.fr/event/95%231

Every property has an "implied default `VALUE`" and for `URL` it's `URI`.

The actual problem here is not the value parameter, but it's in the fact that the it's not a URI!

It should probably be : 

URL;VALUE=URI:http://projet-ode.fr/event/95%231

If iCal permits the former URI then this is an iCal bug. Did you try to report it in apple's radar system?

**Comment by ErrOrnAmE** [comment]
Hi!

I agree that this must be an iCal bug, because if I manually import an ics file containing the line:

```
...
URL:http://projet-ode.fr/event/95%231
...
```
It's fine and iCal take care of the event.

However, if iCal send a vCalendar with the `VALUE=URI`:
```
...
URL;VALUE=URI:http://projet-ode.fr/event/95%231
...
```

And receive one without the `VALUE=URI`:

```
...
URL:http://projet-ode.fr/event/95%231
...
```

Then iCal throws an error.

Always adding the `VALUE=URI` inside an URL property seem to correct this problem.

But would that be a correct workaround even if this is to correct a client bug?

**Comment by ronanguilloux** [comment]
Hi @evert,
just in support of previous @ErrOrnAmE feedback:

> The actual problem here is not the value parameter, but it's in the fact that the it's not a URI!

Well, sorry for my bad initial example ;-) But as @ErrOrnAmE said, the problem described below remains the same with a valid `http//...` URI value. 

I cannot say if sending vCalendar with `URL;VALUE=URI:` as a client and then receiving back just `URL:` without the `VALUE=URI:` from Sabre may be OK or not.

Anyway, it appears so far that Apple's iCal client does not handle such behavior, and throws an error : I'll send an error report to Apple Radar System (thanks for suggesting).

Would you consider to add a workaround (the one we proposed, or something better) in `sabre-vobject` in order to address this particular issue ? 

From our fix example below, we may propose a PR, if you find our solution an interesting one.

**Comment by evert** [comment]
I'm working on a fix for this now. @ronanguilloux / @ErrOrnAmE do you guys have any information regarding which OS X version this was? It will be interesting to record this so a few years down the road we can check if it's still an issue, and perhaps remove the workaround if the last OS X version with the bug becomes rare enough.

**Comment by ronanguilloux** [comment]
Hi @evert, thanks for taking this issue in account ! We encountered the bug on OS X 10.10 Yosemite.

**Comment by evert** [comment]
Thanks for letting me know!
