### ISSUE TITLE
Different formats on valarm trigger duration, list available?

### ISSUE THREAD

**Issue by libasys** [fruux/sabre-vobject#245]
Hi,
i have a question about the different formats of trigger duration, do you have a list of all possible formats where from the different programs are used?
I have written a php valarm function to parse the valarm component, but now i am getting more and more different formats on duration.
Example for a day duration at the moment 3 different formats detected:
-P1D
-PT1D
-P1DT

it would be really awesome if you have a list where are all the possible duration formats are listed!

**Comment by evert** [comment]
Just refer to the spec:

https://tools.ietf.org/html/rfc5545#section-3.3.6

vobject also comes with a parser:

https://github.com/fruux/sabre-vobject/blob/master/lib/DateTimeParser.php#L92
