### ISSUE TITLE
Encoding a photo a base64

### ISSUE THREAD

**Issue by ibarral** [fruux/sabre-vobject#262]
Hello,

I'm trying to include a photo a vCard doing this:

```
$vcard = new VObject\Component\VCard();
$vcard->add('LOGO', '/assets/images/logo.png', ['ENCODING' => 'BASE64', 'TYPE' => 'PNG']);
```

But the problem is that on the file that's generated, the it converts the STRING '/assets/images/logo.png' to base64:

```
L2Fzc2V0cy9pbWFnZXMvbG9nby5wbmc=
```

But not the PNG image itself.

What i'm doing wrong?

Thanks!

**Comment by evert** [comment]
If you want to embed the photo, you need to not pas the filename, but the contents of the file. You can get to the contents with `file_get_contents()`.

**Comment by ibarral** [comment]
Thanks for the tip! I works ok!
