### ISSUE TITLE
Invalid DateTimes in DateTimeParser

### ISSUE THREAD

**Issue by edrush** [fruux/sabre-vobject#289]
Hi,

I'm not sure how to handle this best: when there is an invalid date string coming from an "empty" dateTime column ("0000-00-00 00:00") which turns out to become a date string like "-0001-11-30 00:00:00" I get an Exception.
This is a show stopper to me, I think I'd rather have an invalid ics than an Exception.

What do you mean?

**Comment by evert** [comment]
Since you are talking about a 'column' I'm assuming you are creating an iCalendar object based on database records. Is that correct or am I mistaken?

If that's true, is this referring to a DTSTART? Or something else perhaps? Can you share some code maybe?

**Comment by edrush** [comment]
Hi,

sorry, that's right. DateTime values for DTSTART, DTEND and RECURRENCID come from a database. I could also just ignore them sicne they are not of much use before rendering them with vobject, which I do now as a workaround. But I'm not sure if that's the best way. Do you need more information?

**Comment by evert** [comment]
You should just skip them in that case. I wouldn't call that a work around, but rather the 'sanest approach' to this.

An event with no DTSTART is no event at all, and generating invalid iCalendar objects defeats the purpose of generating iCalendar, because it's likely other iCalendar readers will also break.

**Comment by edrush** [comment]
Right, exactly, I was not sure wether to call it a work around at all. Thanks for your opinion, and your fast answers!
