### ISSUE TITLE
Problem in Vcalendar#getBaseComponent

### ISSUE THREAD

**Issue by GrahamLinagora** [fruux/sabre-vobject#290]
Hello,

I think there is a bug in the getBaseComponent when the filter by component name is triggered : 
```php
...(line 251)
     if ($componentName) {
            foreach ($this->select($componentName) as $child) {
                if ($isBaseComponent($child)) {
                    return $child;
                }
                return null;
            }
        }

     // Searching all components
...
```
IMO, the `return null` should be out of the loop.
For instance if `componentName` is set to `'VEVENT'` and the vcalendar only contains a VTODO, the code will not enter the foreach and will return something because it will search all base components.

(I can issue a PR if you agree there is a problem here)

**Comment by evert** [comment]
I think you're right, this does indeed look broken. This function is for the most part for single-component objects (such as in caldav, imip) so in most cases the base component appears first, but you are right that it would immediately fail if this is not true.

So a PR would definitely be appreciated.

**Comment by GrahamLinagora** [comment]
Please, could this change be included in the current released version of vobject ? It would allow us to use the new sabre 3.1.0 in our project

**Comment by evert** [comment]
If you can wait a week or two I'll do another vobject release. In the meantime, if you are not already using composer to install sabre/dav, do this... because then you can specify to use `dev-master` of vobject instead of the latest stable.

**Comment by GrahamLinagora** [comment]
Ok thanks for the tip
