### ISSUE TITLE
Regression: expand() fails in VObject 4 but works in VObject 3.5

### ISSUE THREAD

**Issue by steffenweber** [fruux/sabre-vobject#293]
First of all, thank you for this awesome library!

I have a test-case that works in VObject 3.5 but fails in VObject 4:

```
<?php
require 'vendor/autoload.php';

$str = "BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Apple Inc.//Mac OS X 10.11.2//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20151204T141751Z
UID:19573090-F6DA-40CC-A1CA-822AFFB0F9BE
RRULE:FREQ=WEEKLY;INTERVAL=5
DTEND;VALUE=DATE:20151219
TRANSP:TRANSPARENT
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
SUMMARY:MySummary
DTSTART;VALUE=DATE:20151218
DTSTAMP:20160121T092634Z
LAST-MODIFIED:20151206T184250Z
SEQUENCE:0
END:VEVENT
END:VCALENDAR";

$start = new DateTime('2016-01-01');
$end = new DateTime('2016-06-01');

$vcalendar = Sabre\VObject\Reader::read($str);
$vcalendar->expand($start, $end);

echo count($vcalendar->VEVENT) . "\n";
```

VObject 3.5.0 prints `4` (correct) but VObject 4.0.2 prints `1` (wrong).

**Comment by evert** [comment]
This was a pretty subtle change, but try:

    $vcalendar->expand($start, $end);

vObject 4 now returns a new VCALENDAR instead of updating the existing one in-line. Definitely confusing but also mentioned in the migration doc:

http://sabre.io/vobject/upgrade_to_4/

**Comment by steffenweber** [comment]
Oops, thank you! :blush:

**Comment by edrush** [comment]
You saved my day...thanks, yeah it was mentioned, but really, surprising...thank you!

**Comment by evert** [comment]
Sorry about this. I thought long and hard if the change would be worth it. Perhaps it wasn't worth it

**Comment by edrush** [comment]
I suppose it was, and you mentioned it, maybe put the mentioned line of code here, too: http://sabre.io/vobject/upgrade_to_4...thanks for answering!

**Comment by evert** [comment]
Do you mean this?

http://sabre.io/vobject/upgrade_to_4/#changes-to-expanding-events

**Comment by edrush** [comment]
Oh, no, sorry, copy-pasted your link :) No, I meant here: http://sabre.io/vobject/recurrence. That was where I looked in the first place and did not really understand your note. Or maybe just add your link there...

**Comment by evert** [comment]
That page actually mentions how to use it and when it changed:

> $newVCalendar = $vcalendar->expand(new DateTime('2012-01-01'), new DateTime('2012-12-31'));

and:

> Note: Before sabre/vobject version 4, the expand() method does not return a new calendar, but it rather edits the entire calendar in-place.

If you have ideas about making it even clearer, you can easily change it here though:

https://github.com/fruux/sabre.io/blob/master/source/vobject/recurrence.md
