### ISSUE TITLE
Default VALUE=URI in PHOTO property prevents BASE64 Images

### ISSUE THREAD

**Issue by florianporada** [fruux/sabre-vobject#294]
You can't add BASE64 encoded images in the `PHOTO` property because of `URI=VALUE` which will be put in front of it by default.

the output is:
`PHOTO;TYPE=PNG;ENCODING=BASE64;VALUE=URI:iVBORw0KGgoAA....`

but it should be:
`PHOTO;TYPE=PNG;ENCODING=BASE64:iVBORw0KGgoAAAANSUhEUgA....`

**Comment by evert** [comment]
Could you share the full source of how you are trying to generate this? It might be easier to correct it based on what I'm seeing =)

**Comment by florianporada** [comment]
Sure. :)
So I have an existing vObject (`$vobject = new Component\VCard()`) and want to add an image with:
`$vobject->add('PHOTO', $data['image'], ['type' => 'PNG', 'encoding' => 'BASE64']);`
`$data['image]` is the BASE64 encoded image.
There are some other Properties which i am adding, like 'TEL', 'FN', but i think this code doesn't matter in this case.

**Comment by evert** [comment]
By default when you create a new vCard object, vCard 4.0 will be used.

vCard 4.0 does not have a `BINARY` type like vCard 3.0 had. The only correct way to embed photos in vCard 4, is by using a `URI` and use the `data:` scheme to encode the photo.

`ENCODING` and `TYPE` are also meaningless in vCard 4 I believe.

**Comment by mschering** [comment]
How can I add 

data:image/jpg;base64,{{THEDATA}} ?

The , is always escaped with a backslash.

**Comment by mschering** [comment]
Any change the escaping will be resolved?
