### ISSUE TITLE
Adding getter

### ISSUE THREAD

**Issue by Razrael** [fruux/sabre-vobject#299]
Hey

I'm using your fantastic library for developing a TYPO3 plugin. Since the templating engine from TYPO3 (Fluid) accesses variables in objects via getter, it would be nice to have a getter directly in Sabre\VObject\Node. Would you consider to add a magic __call() function which would make e.g. getVevent() calls possible?

I tested it with a stupid __call(), which just give the variables back. But you might want to implement an access restriction or something else.

Keep up the great work!

**Comment by evert** [comment]
Hi @Razrael , it doesn't really make sense to me to add code specific to making it easier to work with frameworks such as TYPO3. The request is a bit too specific for that, and I don't think this is particularly useful for everyone using the library. (frankly, I'm worried it just makes things more confusing).

If you really need this, I would recommend creating some wrapper objects for TYPO3 so you can add your own functionality without having to modify the core vobject logic. If you're running into problems with that, or if you need any advice on how to do that I'm happy to help you think of ideas though, just let me know where you're getting stuck.
