### ISSUE TITLE
Accepting invitation only on very first event in series doesn't work

### ISSUE THREAD

**Issue by Michael-Gusev** [fruux/sabre-vobject#306]
Hi. There's some problem with unusual acceptance of invitation.

1. User1 creates event with rrule - every day stop after 3 times and invites User2
2. User2 receives invitation in calendar application, but instead of to accept all events he accepts only first one (in macos calendar simply click on gray event in calendar and click "accept" in popup "only this event")
3. Event of User1 doesn't count acceptance of User2 because code ignores vevent with very first reccurence-id

Proposed solution: https://github.com/fruux/sabre-vobject/pull/305

**Comment by vkomrakov-sugar** [comment]
Proposed solution: #308

**Comment by Michael-Gusev** [comment]
@evert, is there any update?
