### ISSUE TITLE
cannot set multiple TYPE attribute  for setting TYPE=PREF

### ISSUE THREAD

**Issue by doshu** [fruux/sabre-vobject#318]
i have seen that exporting vcard with a TEL set as preferred with a TYPE setted too, in most cases, the vcard line created is 

TEL;TYPE=iphone,cell,voice;TYPE=PREF:4045551212

the TYPE=PREF is separated from other types, so when reimported in a device, the first type group will be setted as the telephone types, but the TYPE=PREF is excluded and used only as preference field.

if i create a vobject setting pref as an attribute like PREF=1, will be valid only for the version 4.0
now, the only 2.1 compatible way is to set TYPE=iphone,cell,voice,pref, but when i import the created vcard, pref is showed in the type string, but it shouldn't

is there a way to set multiple times the TYPE attribute?

**Comment by evert** [comment]
`PREF` is actually a value of `TYPE`.

    TEL;TYPE=x,y

is equivalent to:

    TEL;TYPE=x;TYPE=y

Now if that first syntax doesn't work for a client, then that client is broken. What client are you using that is misinterpreting that syntax?

**Comment by doshu** [comment]
the client is android contacts app and google contacts
after more checks i think that android contacts app does not manage the pref field
so the pref type has been setted as label
