### ISSUE TITLE
[Question] Manipulate X-WR-CALNAME

### ISSUE THREAD

**Issue by Mannshoch** [fruux/sabre-vobject#319]
I got a php script for manipulating an Ical file

every manipulation works  with:
`$vcalendar->VEVENT->SUMMARY = 'Text';`

But manipulate  X-WR-CALNAME not work.
`$vcalendar->X-WR-CALNAME = 'Title';`

How could I do It?

**Comment by evert** [comment]
The PHP syntax for using properties with special characters is this:

     $vcalendar->{'X-WR-CALNAME'} = 'Title';

You can also use this sabre/vobject syntax, which is a little bit faster, but will _not_ overwrite any existing properties, just append them:

         $vcalendar->add('X-WR-CALNAME','Title');

**Comment by Mannshoch** [comment]
Thanks a lot. that works.
Maybe someone could add such an example to http://sabre.io/vobject/icalendar/

**Comment by evert** [comment]
That someone could be you! https://github.com/fruux/sabre.io/tree/master/source/vobject

**Comment by Mannshoch** [comment]
OK did it --> https://github.com/fruux/sabre.io/issues/86
