### ISSUE TITLE
Recurring events are expanded not correct if DTSTART is included in EXDATE

### ISSUE THREAD

**Issue by scriptPilot** [fruux/sabre-vobject#321]
If I create a recurring event in Outlook and remove the first instance, expand is not working properly. There is no information copied like Summary, Location etc.

**Comment by evert** [comment]
This doesn't sound like a sabre/vobject bug to me, but an outlook bug?

Either that, or I don't really understand the problem. Would you be able to demonstrate the issue with a code sample?

**Comment by scriptPilot** [comment]
Outlook is a bug itself ;-) ... but I think it should be managed by expand() properly.

Original ICS snippet ...

`DTEND;TZID="W. Europe Standard Time":20160519T130000
DTSTART;TZID="W. Europe Standard Time":20160519T120000
EXDATE;TZID="W. Europe Standard Time":20160519T120000,20160602T120000,20160
	630T120000
LAST-MODIFIED:20160601T110505Z
RRULE:FREQ=WEEKLY;COUNT=4;INTERVAL=2;BYDAY=TH;WKST=MO`

So as you can see, the start date is the 19/05/16, which is also listed as EXDATE.

In the result, all the data as location, summary and so on is not copied into the expanded events. The events itself are beeing created by expand.

Thank you for support!

**Comment by evert** [comment]
Could you please provide a full sample?

**Comment by scriptPilot** [comment]
See attached the ics file.

Regards

**Comment by scriptPilot** [comment]
[example.zip](https://github.com/fruux/sabre-vobject/files/299558/example.zip)

**Comment by evert** [comment]
As far as I can tell, the behavior is actually correct.

The ics file contains two `VEVENT` blocks with the same `UID`.

There is the 'master' event, with the following info:

```
BEGIN:VEVENT
ATTENDEE;CN="Moni";RSVP=TRUE:mailto:moni@dax.de
DESCRIPTION:\n
DTEND;TZID="W. Europe Standard Time":20160519T130000
DTSTAMP:20160112T101353Z
DTSTART;TZID="W. Europe Standard Time":20160519T120000
EXDATE;TZID="W. Europe Standard Time":20160519T120000,20160602T120000,20160
	630T120000
LAST-MODIFIED:20160601T110505Z
LOCATION:Meeting room
ORGANIZER;CN="Max":mailto:max@dax.de
PRIORITY:5
RRULE:FREQ=WEEKLY;COUNT=4;INTERVAL=2;BYDAY=TH;WKST=MO
SEQUENCE:0
SUMMARY;LANGUAGE=de:A350 SEDC/SEDB Drumbeat
UID:140000008200E00074C5B7101A82E00800000000D0B884522A4DD101000000000000000
	01000000025D1D02B2A5385458226E91C8AABF67E
END:VEVENT
```

This event recurs every 2 weeks on a thursday for a maximum of 4 times. But it also excludes 3 out of those 4 events, leaving only 1 event.

That one event is also embedded in the ics:

```
BEGIN:VEVENT
DTEND:20160616T110000Z
DTSTAMP:20160603T152427Z
DTSTART:20160616T100000Z
LAST-MODIFIED:20160407T172901Z
PRIORITY:5
RECURRENCE-ID:20160616T100000Z
SEQUENCE:0
TRANSP:OPAQUE
UID:140000008200E00074C5B7101A82E00800000000D0B884522A4DD101000000000000000
	01000000025D1D02B2A5385458226E91C8AABF67E
END:VEVENT
```

So, because the event is also embedded here, it serves as the overridden event. We are not supposed to automatically copy any information from the master event, so this is 100% expected.

If you take out the second `VEVENT` and you run expand, you do get the correct instance.

**Comment by evert** [comment]
Yes that would be the expected behavior in iCalendar. It is _required_ for a client to copy all the information into the overridden instances. I'm very surprised that this is not the case for Outlook.

One option would be to create some kind of 'outlook mode' for the recurrence iterator. I'm not necessarily against that, especially if this behavior still occurs in the latest Outlook versions.

**Comment by scriptPilot** [comment]
To be honest that was what I have expected from the FORGIVEN mode ;-)
Could I support in any way? I would prefer to include that function in VObject rather that code just for me a quick workaround ...

**Comment by evert** [comment]
The issue is that the data outlook produces is not invalid, but it has a different meaning than outlook intends.

The meaning of the object is 'please strip the description and summary from the overidden event' which is what we are doing.

If you are interested in building an outlook workaround, it would have to be an option on the Recur\EventIteratorclass.

If you're interested in building this, and you can submit it as a pull request + unit test, I'll happily add it to vobject

**Comment by scriptPilot** [comment]
So, that is my Workaround:
`$outlookCalendar = Sabre\VObject\Reader::read($calendarFileContent, Sabre\VObject\Reader::OPTION_FORGIVING);
// Add missing information for recurring events (Outlook workaround)
                    $eventData = [];
                    foreach ($outlookCalendar->VEVENT as $e) {
                    
                        // First occurence of UID
                        if (!isset($eventData[(string)$e->UID])) {
                            $eventData[(string)$e->UID] = [
                                'SUMMARY' => $e->SUMMARY,
                                'LOCATION' => $e->LOCATION,
                                'DESCRIPTION' => $e->DESCRIPTION,
                                'ORGANIZER' => $e->ORGANIZER,
                                'ATTENDEE' => $e->ATTENDEE,
                                'OUTLOOKSTATUS' => $e->{'X-MICROSOFT-CDO-BUSYSTATUS'}
                            ];
                            
                        // Repeating occurence of UID
                        } else {                        
                            if (!isset($e->SUMMARY)) $e->SUMMARY = $eventData[(string)$e->UID]['SUMMARY'];
                            if (!isset($e->LOCATION)) $e->LOCATION = $eventData[(string)$e->UID]['LOCATION'];
                            if (!isset($e->DESCRIPTION)) $e->DESCRIPTION = $eventData[(string)$e->UID]['DESCRIPTION'];
                            if (!isset($e->{'X-MICROSOFT-CDO-BUSYSTATUS'})) $e->{'X-MICROSOFT-CDO-BUSYSTATUS'} = $eventData[(string)$e->UID]['OUTLOOKSTATUS'];
                            if (!isset($e->ORGANIZER)) $e->ORGANIZER = $eventData[(string)$e->UID]['ORGANIZER'];                         
                            if (!isset($e->ATTENDEE)) {
                                foreach ($eventData[(string)$e->UID]['ATTENDEE'] as $attendee) {
                                    $e->add('ATTENDEE', (string)$attendee, ['CN'=>$attendee['CN'], 'CUTYPE'=>$attendee['CUTYPE']]);                       
                                }
                            }
                        }
                        
                    }`

**Comment by scriptPilot** [comment]
So ... that is my workaround:

[workaround.zip](https://github.com/fruux/sabre-vobject/files/302516/workaround.zip)

**Comment by evert** [comment]
A zip is a bit hard to review, but if it works for you, I'm glad!

**Comment by scriptPilot** [comment]
I have not settet the dev. Environment for GitHub - but if somebody has the same Problem I hope my but of code will Support! :-)

**Comment by safadig** [comment]
Not sure if related but I am reading ical from Time ly All-in-One WP Event Plugin. Works well except for recurring events are not showing with or without expand command:
~~~
BEGIN:VEVENT
UID:ai1ec-60@staff.cliniclocal.com
DTSTAMP:20160608T232947Z
CATEGORIES;LANGUAGE=en-US:Oregon
CONTACT:
DESCRIPTION:
DTSTART;TZID=America/New_York:20160609T000000
RRULE:FREQ=MONTHLY;COUNT=365;BYDAY=2TH
SEQUENCE:0
SUMMARY:ORE: Tricia\, Pam
URL:http://staff.allergyclinicohiocal.com/event/ore-xyz-2/
X-COST-TYPE:free
X-INSTANT-EVENT:1
END:VEVENT
~~~

**Comment by evert** [comment]
Please open a new ticket, include a full iCalendar file + code snippet that demonstrates the issue!
