### ISSUE TITLE
[Question] How to remove single VEVENT items

### ISSUE THREAD

**Issue by scriptPilot** [fruux/sabre-vobject#322]
If I Loop a calendar with multiple VEVENT objects, how could I remove a specific one? Unset doest work.

**Comment by evert** [comment]
You can call the `remove()` function on the parent.

For example:

    $vcalendar->remove($vcalendar->VEVENT[5]); // removes the 6th VEVENT.

**Comment by scriptPilot** [comment]
Thanks!
