### ISSUE TITLE
X- component name non-conformity by 3rd-party software

### ISSUE THREAD

**Issue by jpirkey** [fruux/sabre-vobject#323]
I had a customer with a google calendar that included a component as follows:

```ical
X-ENTOURAGE_UUID:F0745CC0-B278-400C-8185-11DBAF63E98D`
```

and the validator fails with:
`Error: Invalid Mimedir file. Line starting at 24497 did not follow iCalendar/vCard conventions`

simply changing the component name to `X-ENTOURAGE-UUID` validates correctly (which makes sense).  As you know the spec doesn't "allow" `_` in component names.  So my question to you is this something you guys is have encountered before and should I just replace the `X-ENTOURAGE_UUID` with `X-ENTOURAGE-UUID` before trying to validate or should I submit a pull request to update the validator to add support for underscores in `X-` component names?

Thanks for your help.

**Comment by evert** [comment]
Hi @jpirkey ,

We have encountered them before. We added a `FORGIVING` setting to the parser, that will allow you to read these properties. But this is not the default.

It's important for us to stay strict. If you don't want to be strict, you can opt in to looseness ;)

Hope this helps, if not, feel free to follow-up here.
