### ISSUE TITLE
VCard Photo returns wrong valueType for some vCards

### ISSUE THREAD

**Issue by georgehrke** [fruux/sabre-vobject#325]
Discovered on Sabre/VObject 3.5.0
reproducible on Sabre/VObject 4.1.0

PHP script to reproduce error:
```php
<?php

include 'vendor/autoload.php';

$data1 = "BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:-//Sabre//Sabre VObject 3.5.0//EN\r\nUID:12345\r\nFN:12345\r\nN:12345;;;;\r\nPHOTO;TYPE=JPEG:http://example.org/photo.jpg\r\nEND:VCARD\r\n";
$data2 = "BEGIN:VCARD\r\nVERSION:4.0\r\nPRODID:-//Sabre//Sabre VObject 3.5.0//EN\r\nUID:12345\r\nFN:12345\r\nN:12345;;;;\r\nPHOTO:data:image/jpeg;MTIzNDU=\r\nEND:VCARD\r\n";

$v1 = \Sabre\VObject\Reader::read($data1);
$v2 = \Sabre\VObject\Reader::read($data2);

echo "V1: " . $v1->PHOTO->getValueType();
echo "\n-----------------\n";
echo "V2: " . $v2->PHOTO->getValueType();
```

results in ...

```
V1: BINARY
-----------------
V2: URI
```

expected ...
```
V1: URI
-----------------
V2: BINARY
```

**Comment by evert** [comment]
Super weird

**Comment by evert** [comment]
Ah I know why this is happening, both of the vcards are broken.

In vCard version 3.0, by default every `PHOTO` has the `BINARY` type, _unless_ `VALUE=URI` is specified. Since this vCard does not have `VALUE=URI` we assume it's `BINARY`. This is the correct implementation of this vcard.

In vCard version 4.0, `BINARY` no longer exists. Everything is a `URI` including the vCard you posted here. As you can see there, the photo is embedded inline using the `data:` uri scheme.

So the output is actually correct.

The question is then, do you know what software generates these broken vcards? Can you report a bug there?

**Comment by georgehrke** [comment]
@DeepDiver1975 took them from Wikipedia 🙈

**Comment by evert** [comment]
Sorry to clarify, only the first vCard is really broken... the second one is fine =)

**Comment by georgehrke** [comment]
allegedly both are valid according to Wikipedia (which doesn't mean anything ^^).
see PHOTO row in https://en.wikipedia.org/wiki/VCard#Properties

**Comment by evert** [comment]
From https://tools.ietf.org/html/rfc2426#section-3.1.4

> Type value: A single value. The default is binary value. It can also
> be reset to uri value. The uri value can be used to specify a value
> outside of this MIME entity.

and:

> Type example:

        PHOTO;VALUE=uri:http://www.abc.com/pub/photos
         /jqpublic.gif

Wikipedia is wrong and @DeepDiver1975 should feel bad using Wikipedia as a substitute for a spec ;)

**Comment by evert** [comment]
Fixed the wikipedia page

**Comment by DeepDiver1975** [comment]
:see_no_evil:

**Comment by evert** [comment]
Lol :P

**Comment by georgehrke** [comment]
Is it intended that `getValue()` returns `data:image/jpeg;base64,MTIzNDU=` for `PHOTO:data:image/jpeg;base64,MTIzNDU=` though? 

I see that `data:image/jpeg;base64` are technically no vcard parameters, but I would expect `getValue()` to return 12345. (while it would actually expect `getRawMimeDirValue()` to return the entire Value.)

**Comment by evert** [comment]
It's expected. This allows you to place it directly in an `<img>` tag or pass `fopen()`. I don't think it makes sense for a URI property to return a URI in some cases for getValue() and a binary blob in other cases. The behavior shouldn't change based on the type of uri (whether thats http, https or data).

**Comment by evert** [comment]
To get that binary blob, all you have to do is "file_get_contents()" btw!

**Comment by georgehrke** [comment]
> To get that binary blob, all you have to do is file_get_contents() btw!

I already see script kiddies uploading vcards with PHOTO:file:///etc/passwd 🙈

**Comment by evert** [comment]
That is a really good point (and scary)

**Comment by evert** [comment]
or `javascript:` in a frontend

**Comment by georgehrke** [comment]
@LukasReschke Any hints how to parse this safely?

Is it safe to use `parse_url` and make sure that the scheme is data?

**Comment by evert** [comment]
Use `Sabre\Uri\parse()` for a similar, but easier/safer option =) 

Anyway, if it's `data://` you can safely assume that you'll end up reading *just* what's in the iCalendar. However, there's no guarantee about its contents. Dunno what you end up doing with the image, but it could also *not* be an image.

**Comment by bohwaz** [comment]
Just found out that DAVx5 on Android does return this kind of PHOTO field.

A safe way to parse it would be:

```

function getBinaryValue(VObject\Property $p): ?string
{
	$type = $p->getValueType();
	$value = $p->getValue();

	if ($type === 'URI') {
		if (!preg_match('/^data:image\/(?:jpe?g|gif|png|webp|svg\+xml);base64,/', $value, $match)) {
			return null;
		}

		$value = substr($value, strlen($match[0]));
		var_dump($value); exit;
		$value = base64_decode($value);
		return $value;
	}
	elseif ($type === 'BINARY') {
		return $value;
	}
	else {
		return null;
	}
}

```
