### ISSUE TITLE
Endless loop in RRuleIterator if BYMONTH is invalid

### ISSUE THREAD

**Issue by PHPGangsta** [fruux/sabre-vobject#328]
I'm using vobject 4.1.0

I have the following file:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//something//DE
CALSCALE:GREGORIAN
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VEVENT
UID:20160103T123408CET-8725fEVfDC
DTSTAMP:20160103T113408Z
DTSTART;VALUE=DATE:20150124
DTEND;VALUE=DATE:20150125
RRULE:FREQ=YEARLY;BYMONTHDAY=24;BYMONTH=0
SUMMARY:important date
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR
```

The problem here is the BYMONTH=0. It's invalid, but there is no Exception thrown, and my script (in this case the migration17.php script) runs into an endless loop. The same happens if BYMONTH=bla or something else other than the numbers 1 to 12...

The loop occurs in line 576 (maybe also in 605 in other situations):
https://github.com/fruux/sabre-vobject/blob/master/lib/Recur/RRuleIterator.php#L576
```php
                do {
                    $currentMonth++;
                    if ($currentMonth > 12) {
                        $currentYear += $this->interval;
                        $currentMonth = 1;
                    }
                } while (!in_array($currentMonth, $this->byMonth));
```

The loop runs from 1 to 13, resets to 1, goes up to 13, and so on... and it runs until it's 0 ;-)

I'm willing to create a PR to throw an Exception if there is an invalid value found in BYMONTH (should be in line 720).

Should there also be some checks for other invalid values, like BYSECOND, BYMINUTE, BYHOUR, BYMONTHDAY, BYYEARDAY, BYWEEKNO, WKST and the others?

For example, if I have this invalid WKST:
`RRULE:FREQ=WEEKLY;UNTIL=20171007T000000Z;WKST=bla;BYDAY=TU,TH`
I get the following Notice, and I guess strange things happen after that:
`Notice: Undefined index: BLA in vendor\sabre\vobject\lib\Recur\RRuleIterator.php on line 405`

**Comment by evert** [comment]
I agree that in cases where clearly invalid values are provided (BYMONTH=0), we should throw an `InvalidDataException`. It would be nice if those rules were also added to the validate() function so we get early detection when the user uploads invalid iCalendar data (and not after the fact when recurrence first kicks in)

**Comment by PHPGangsta** [comment]
I will close this issue. The fix has been merged
https://github.com/fruux/sabre-vobject/pull/333

and some rules have been added to the Recur->validate() function
https://github.com/fruux/sabre-vobject/pull/338
