### ISSUE TITLE
RRULE: BYWEEKNO and BYYEARDAY not respected

### ISSUE THREAD

**Issue by PHPGangsta** [fruux/sabre-vobject#340]
I'm using vobject 4.1.0

I was just trying some things with BYWEEKNO and BYYEARDAY, and I saw that it's not used in the calculations. It's parsed, and put into the protected variable `$this->byWeekNo` / `$this->byYearDay` in the RRuleIterator, but it's not used anywhere.
https://github.com/fruux/sabre-vobject/blob/master/lib/Recur/RRuleIterator.php#L715

I guess they should be used for calculations in the `nextYearly()` method.

Is there a reason that they are not implemented?

**Comment by evert** [comment]
There's a number of recurrence rules not implemented. The main reason is that it's a bit difficult, and most of them are unused. I've basically added them on an as-needed basis and you're the first to ask ;)

**Comment by evert** [comment]
Fixed via #341
