### ISSUE TITLE
Missing Exchange Time Zone mapping

### ISSUE THREAD

**Issue by jpirkey** [fruux/sabre-vobject#344]
As mentioned in issue #248, it looks like a response from `webcal://outlook.office365.com/owa/...` is returning timezones that aren't included in the exchange timezone mapping. Below is an example of weird timezone value:
```php
$feed = <<<ICS
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
X-WR-CALNAME:Calendar
BEGIN:VTIMEZONE
TZID:(UTC-05:00) Eastern Time (US & Canada)
BEGIN:STANDARD
DTSTART:16010101T020000
TZOFFSETFROM:-0400
TZOFFSETTO:-0500
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=1SU;BYMONTH=11
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:-0500
TZOFFSETTO:-0400
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=2SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
DESCRIPTION:Quick meeting
UID:040000003232E00074C5B7876A82E00800000000FD0CCC288FF8D101000000000000000
 01000000006F59CB9230499438F3AB6F603BBFA69
SUMMARY:STAFF MEETING
DTSTART;TZID="(UTC-05:00) Eastern Time (US & Canada)":20160802T083000
DTEND;TZID="(UTC-05:00) Eastern Time (US & Canada)":20160802T090000
CLASS:PUBLIC
PRIORITY:5
DTSTAMP:20160822T184151Z
TRANSP:OPAQUE
STATUS:CONFIRMED
SEQUENCE:0
LOCATION:
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-CDO-INSTTYPE:0
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
ICS;
```

This timezone seems to somewhat match (minus the ampersand) the text in the [Microsoft Time Zone Index Values](https://msdn.microsoft.com/en-us/library/ms912391(v=winembedded.11).aspx), but odd they don't use "Name of Time Zone".  

So the question is do you want me to create a pull request for this or do you want to wait for Issue #248 to be implemented?

**Comment by evert** [comment]
Oh man. Coming straight from a microsoft product. That's annoying and certainly relevant enough to create a workaround for =(

**Comment by jpirkey** [comment]
I'll fork and create a pull request for it (unless you are planning on doing it).  Just wanted to make sure you were good with that before doing so.
