### ISSUE TITLE
FREEBUSY REPORT for calendar throws InvalidArgumentException (You can only pass strings or \Sabre\VObject\Component arguments to setObjects)

### ISSUE THREAD

**Issue by dcywka** [fruux/sabre-vobject#348]
Method Sabre\VObject\FreeBusyGenerator::setObjects() throws InvalidArgumentException when passed array of resources as argument. (https://github.com/fruux/sabre-vobject/blob/master/lib/FreeBusyGenerator.php#L160)

It happens when trying to access calendar's FREEBUSY report like this:
![request](https://cloud.githubusercontent.com/assets/10763870/18836580/efbd39f2-8400-11e6-813c-acea1234d23c.png)
![response](https://cloud.githubusercontent.com/assets/10763870/18836581/efc3ae54-8400-11e6-9e30-62ee2836bb0c.png)

**Comment by evert** [comment]
Confirmed!
