### ISSUE TITLE
Vevent::isInTimeRange and EventIterator::fastFoward does not work well for allDay event

### ISSUE THREAD

**Issue by strokyl** [fruux/sabre-vobject#351]
Considering the following vevent which is an allDay event that is repeated every day forever: 

`BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
CREATED:20161028T122603Z
LAST-MODIFIED:20161028T122614Z
DTSTAMP:20161028T122614Z
UID:fa7bdace-5732-48d2-8c54-9f4eabc1fe6e
SUMMARY:test allDay rec 
RRULE:FREQ=DAILY
DTSTART;VALUE=DATE:20161027
DTEND;VALUE=DATE:20161028
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR`

The `VEvent::isInTimeRange` does not work well on such instance. For example if it is called with `new \DateTime('2016-10-31'), new \DateTime('2016-12-12')` it will return false instead of true.

This is because inside this method, the following line (49):

`$it->fastForward($start);`

will move to the instance that end just before 2016-10-31. In fact this instance end exactly at 2016-10-31, this is what cause `EventIterator::fastForward` to move to the wrong instance.

**Comment by strokyl** [comment]
Her is my PR for this issue : https://github.com/fruux/sabre-vobject/pull/352

**Comment by evert** [comment]
Hi @strokyl ,

This is an interesting problem and one thing I've spent some time thinking about in the past. The question really is: is the end-time inclusive or exclusive?

I settled on exclusive, because this is also how DTEND works. The reasoning is that if I have an event that goes from 2pm - 3pm and another event that goes from 3pm and 4pm, the two times would be specified as:

    14:00 - 15:00
    15:00 - 16:00

And not something like:

    14:00:00 - 14:59:59
    15:00:00 - 15:59:59

Because in the second case there is exactly one second where I'm not in either meeting. This tells me that the start and end times basically don't describe "a specific second in a day" but rather "a specific moment in time". Things that end exactly at that moment, and that begin at that exact moment do not overlap with each other, they come right after each other.

Therefore in your example if your end time is 2016-10-31 00:00:00, and a new event begins at that very same moment, these two times do not overlap either.

So yea, this is by design and actually only became this way after a several versions in the past and I realized the problems with this.

**Comment by evert** [comment]
If you think I'm wrong, perhaps you can explain your use-case better and perhaps figure out what a more correct way would be to express something like this.

**Comment by strokyl** [comment]
I can understand you position about `EventIterator::fastForward`. But for the moment, there is an issue for sure about `VEvent::isInTimeRange` and allDay event that cause sabre-dav REPORT to exclude allDay event in some case. 
For example, if you consider the ICS I gave you when I opened the issue, it represents an allDay recurring event that is repeated everyday since the 27 October 2016.
When I ask Sabre-dav via a report to give me all the event between the 31 October 2016 and the 12 december 2016, it does not return me any instance of this recurring event. And this issue is because of a bad comportment of `VEvent::isInTimeRange`
If you do not want to change the code of `EventIterator::fastForward`, then I have a suggestion to fix this issue in this PR: https://github.com/fruux/sabre-vobject/pull/353

**Comment by evert** [comment]
Hi @strokyl,

It doesn't make sense that the behaviour of time ranges EVERYWHERE means that the the end time is exclusive, except this one place.

Can you explain why you think you need this? Are you dealing with a buggy client ? Is one of your users having a problem ? Help me understand

**Comment by strokyl** [comment]
Hello @evert,

I think we do not understand each other. I think before speaking about the better way to correct the bug, we should agree one the bug.

I wrote a test on my PR that summarize the bug of the method `VEvent::isInTimeRange`:
https://github.com/linagora/sabre-vobject/blob/d2d12d5de5a05f39d0f1e0a3442167f13bf3b5f2/tests/VObject/Component/VEventTest.php#L85 (line 85 to line 89).

This test is about creating an event that recur every day and that is an allDay. The first instance of this event is the 27 october 2016.
After creating this event, I check that isInTimeRange method  called with the range starting at the 31 October 2016 (midnight) and finishing the 12 December 2016 return true.

Without my PRs this test that I consider correct fail.

About yours questions:

> Can you explain why you think you need this?

Because, our team find a bug on our product that use Sabre-dav as a Caldav backend. The bug was that allDay that recur forever only get displayed the first month were there start. But disappear for the next month. By tracking this bug, I found that the issue was from the answer of Sabre for REPORT request on a specific time-range.
So we need to fix this bug in order to fix our product.

> Are you dealing with a buggy client

I checked creating the allDay recurring event with Thunderbird Lightning. The problem persist on our client and I tested with a curl request that the event creating is missing from the response of a REPORT request on Sabre-dav.

> Is one if your usrs having a problem ?

No, our product is currently in development so we do not have real user yet.

**Comment by strokyl** [comment]
Also I just read again your first comment about my first PR and you say:

> This is an interesting problem and one thing I've spent some time thinking about in the past. The question really is: is the end-time inclusive or exclusive?

> I settled on exclusive..

And the thing is that [the first PR I proposed](https://github.com/fruux/sabre-vobject/pull/352/commits/24ba906b6e71536d317c8abb9f5b9d4cbef07c5c) actually move the implementation of `EventIterator::fastForward` from end inclusive to end exclusive! So I don't understand why you don't agree with it.

**Comment by evert** [comment]
Ah thank you, I really understand the problem now. I need to think a little bit about this

**Comment by evert** [comment]
I also agree now that your first PR is actually the correct one. Sorry for not analyzing this better, great job at finding the problem and submitting a correct fix.

**Comment by strokyl** [comment]
Thank you

**Comment by evert** [comment]
Hi @strokyl ,

I spent all night going through all the unhandled github notifications. Finally got to this, and I just did a release. Sorry for the wait.
