### ISSUE TITLE
VALARM not working on macOS sierra Calendar

### ISSUE THREAD

**Issue by edalzell** [fruux/sabre-vobject#361]
I create an ICS file:
```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 4.1.2//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:sabre-vobject-b33288d5-7c94-4ce8-b6e5-10f6c88248e7
DTSTAMP:20170112T203553Z
DTSTART:20161109T080000Z
DTEND:20161109T080000Z
SUMMARY:foo
DESCRIPTION:bar
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER:-P1H
DESCRIPTION:foo
END:VALARM
END:VEVENT
END:VCALENDAR
```

When I double click on this file on my mac, Calendar opens but there is no reminder set at all.

What am I doing wrong?

**Comment by evert** [comment]
Hi,

The `TRIGGER` property is in the wrong format. I think the alarm doesn't go off because of this. It should be `-PT1H`

**Comment by edalzell** [comment]
Tried that as well, still not working. But clearly not a VObject issue.

**Comment by DominikTo** [comment]
Did you compare your `VALARM` with one generated by Sierra Calendar.app itself?
A `VALARM` generated by it looks like this. Maybe it requires the `UID` property in the `VALARM`?

```
BEGIN:VALARM
X-WR-ALARMUID:some-uuid-foo
UID:some-uuid-foo
TRIGGER:-PT1H
DESCRIPTION:Event reminder
ACTION:DISPLAY
END:VALARM
```

**Comment by DominikTo** [comment]
Hm, nope. Also works fine for me with stripped out `UID` and `X-WR-ALARMUID`:

```
BEGIN:VALARM
TRIGGER:-PT1H
DESCRIPTION:Event reminder
ACTION:DISPLAY
END:VALARM
```

**Comment by edalzell** [comment]
Confirmed, works for me too. I had a few things wrong. Thanks for helping!
