### ISSUE TITLE
create event without timezone

### ISSUE THREAD

**Issue by panpekar** [fruux/sabre-vobject#362]
Hello, 
I want create calendar with event without datetime. But method `setValue` in `DateTime` call method `setDateTimes` https://github.com/fruux/sabre-vobject/blob/master/lib/Property/ICalendar/DateTime.php#L72 only with one parameter. I need call it with `$this->setDateTimes([$value], $isFloating = TRUE);` How can I do this? Is there any different way or you only forgot on this parameter?

```php
$vcalendar->add('VEVENT', [
 'SUMMARY' => $description,
 'DTSTART' => new DateTime($rangeItem['interval']['from']),
 'DTEND' => new DateTime($rangeItem['interval']['to']),
]);
```

**Comment by panpekar** [comment]
$vevent = new Sabre\VObject\Component\VEvent($vcalendar, 'VEVENT');
				$dtstart = new Sabre\VObject\Property\ICalendar\Date($vcalendar, 'DTSTART');
				$dtstart['VALUE'] = 'DATE';
				$dtstart->setDateTime($rangeItem['interval']['from'], TRUE);
				$dtend = new Sabre\VObject\Property\ICalendar\Date($vcalendar, 'DTEND');
				$dtend['VALUE'] = 'DATE';
				$dtend->setDateTime($rangeItem['interval']['to']->modifyClone('+1 day'), TRUE); // every external calendar services (google calendar, airbnb) show by one day less without modify
				$summary = new Sabre\VObject\Property\FlatText($vcalendar, 'SUMMARY', $description);
				$vevent->add($dtstart);
				$vevent->add($dtend);
				$vevent->add($summary);
				$vcalendar->add($vevent);

**Comment by panpekar** [comment]
Okay, I created event without timezone and also without time but I don't know if is it best solution, but it works.

```php
$vevent = new Sabre\VObject\Component\VEvent($vcalendar, 'VEVENT');
$dtstart = new Sabre\VObject\Property\ICalendar\Date($vcalendar, 'DTSTART');
$dtstart['VALUE'] = 'DATE';
$dtstart->setDateTime($from, TRUE);
$dtend = new Sabre\VObject\Property\ICalendar\Date($vcalendar, 'DTEND');
$dtend['VALUE'] = 'DATE';
$dtend->setDateTime($to, TRUE);
$summary = new Sabre\VObject\Property\FlatText($vcalendar, 'SUMMARY', $description);
$vevent->add($dtstart);
$vevent->add($dtend);
$vevent->add($summary);
$vcalendar->add($vevent);
```

**Comment by evert** [comment]
Here's another way, which might work for you:

```php
$vevent = $vcalendar->add('VEVENT', [
 'SUMMARY' => $description,
]);
$vevent->add('DTSTART', new DateTime($rangeItem['interval']['from']), ['VALUE' => 'DATE']);
$vevent->add('DTEND', new DateTime($rangeItem['interval']['to']), ['VALUE' => 'DATE']);
```

Hope that helps. It's a lot shorter =)
