### ISSUE TITLE
Adding DTSTART;TZID/

### ISSUE THREAD

**Issue by jigsawsoul** [fruux/sabre-vobject#368]
How do I add DTSTART;TZID and DTEND;TZID
e.g.
```
DTSTART;TZID=Central Standard Time:20130325T133000
DTEND;TZID=Central Standard Time:20130325T140000
```
I have tried the follow
```
$vcalendar->add(['DTSTART;TZID' => $windowsTimeZone]);

$vcalendar->DTSTARTTZID = ''
```

But with no luck

Thank you for your help.
Richard

**Comment by evert** [comment]
You really should not use non-standard timezone identifiers like the windows ones. It's a pretty bad idea. Instead, you should use the olson timezone identifiers.

You can easily do this with for example:

    $vevent->add('DTSTART', new DateTime('..', new DateTimeZone('...')));

However, if you insist on using windows timezone ids, you can still do this:

    $vevent->add('DTSTART', '...', ['TZID' => '...']));

**Comment by jigsawsoul** [comment]
Thanks for the quick reply Evert.

Unfortunately, my client needs the windows timezone ids. I have tried the code from above but with no luck.
```
$vcalendar = new VObject\Component\VCalendar();
$vcalendar->add('DTSTART', new \DateTime($this->start_date), ['TZID' => $windowsTimeZone]);
```
**Output:** `DTEND:20170211T000000Z`

Seems odd, maybe you could point out where I am going wrong?

Thanks
