### ISSUE TITLE
VObject Expand function don't get right times during DAYLIGHT SAVINGS dates

### ISSUE THREAD

**Issue by surre1** [fruux/sabre-vobject#369]
<pre>
Hi!

I have tested the expand-funktion: $vcalendar->expand(new DateTime('...'), new DateTime('...'));
 to expand events.
Both with latest v3 and latest v4 (4.1.2) they get the wrong time during the days of daylight savings (e.g: after 29th of Mars and before 25th of Oct). Even though the ics-file says it's localtime (DTSTART;TZID=Europe/Stockholm:20170309T173000). = No Z at end - no changes of time due to daylight savings.

Here is a printout of the DTSTART of all the expanded events, as you see the time changes when in Daylight saving zone.
--------------------------------------------------------------------------------------------
...
## 2017-04-04 16:30:00 ##
...
## 2017-11-07 17:30:00 ##
...
--------------------------------------------------------------------------------------------

Hope it's doable to fix this as soon as possible! 
Br
/Mattias

Part of the events.ics file
--------------------------------------------------------------------------------------------
...
BEGIN:VTIMEZONE
TZID:Europe/Stockholm
X-LIC-LOCATION:Europe/Stockholm
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
...
BEGIN:VEVENT
DTSTART;TZID=Europe/Stockholm:20170309T173000
DTEND;TZID=Europe/Stockholm:20170309T190000
RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20170601T153000Z;INTERVAL=1;BYDAY=TH
DTSTAMP:20170227T143256Z
UID:xyz@google.com
CREATED:20170226T173626Z
DESCRIPTION:
LAST-MODIFIED:20170226T173626Z
LOCATION:
SEQUENCE:1
STATUS:TENTATIVE
SUMMARY:Test
TRANSP:OPAQUE
END:VEVENT
...
--------------------------------------------------------------------------------------------

testScript.php
--------------------------------------------------------------------------------------------
<?php

use Sabre\VObject;
use Sabre\Xml;

include 'vendor/autoload.php';

$vcalendar = VObject\Reader::read(
    fopen('event.ics','r')
);

$vcalendar->expand(new DateTime('2017-01-01'), new DateTime('2017-12-31'));

foreach($vcalendar->VEVENT as $event) {
$stime = $event->DTSTART->getDateTime()->format('Y-m-d H:i:s');
echo "## $stime ## ";
echo "\n";
}

?>
--------------------------------------------------------------------------------------------
</pre>

**Comment by evert** [comment]
You are seeing shifting times because expand also converts everything to UTC. From a Europe/Stockholm perspective these times are in fact correct.

**Comment by surre1** [comment]
Hi, ok I might have missed something here...


could you please help me with a code snippet for getting the correct time values?


Br

/Mattias


________________________________
