### ISSUE TITLE
Property\Text should handle CHARSET encoding for VCARD v2.1

### ISSUE THREAD

**Issue by clue** [fruux/sabre-vobject#41]
Now that we finally have a `Property::getValue()` (*hooray*) that returns the value in a datatype native to PHP without all the base64/quoted-printable encoding fuzz, I think it should also support (de)encoding according to its CHARSET parameter. Specifically MS outlook (and very likely others) usually uses the native system encoding and includes this in the CHARSET declaration only once special characters (outside of the standard ASCII range?) are included in the property value.

Now that VObject v3 is right around the corner, I'd vote for including it before the feature freeze to avoid breaking the API once again.

I'll see if I can contribute some patches, but I wanted to post this right away.

**Comment by Hywan** [comment]
ping?

**Comment by evert** [comment]
It's a feature request, and it's still open. Not sure what else I could say about this...

**Comment by Hywan** [comment]
We have #43 opened. Is it ready for a review?

**Comment by evert** [comment]
The patch seems a bit incomplete, but unfortunately I haven't been able to get more into it yet...

**Comment by evert** [comment]
Sorry it took 2 years to fix this, but I finally committed a patch that will cause the parser to automatically decode properties that have `CHARSET` specified to UTF-8. Currently only ISO-8859-1 is supported, but if you need more encodings, let me know.

**Comment by clue** [comment]
Thanks @evert, the patch looks good to me and is much appreciated!

> Currently only ISO-8859-1 is supported, but if you need more encodings, let me know.

The original patch in #43 explicitly tested against `CHARSET=Windows-1252`. This is what a German MS Outlook version exported, so I suppose it makes sense to also take Windows' code pages into account here.

**Comment by evert** [comment]
I'll definitely add support for WIndows-1252 then!
