### ISSUE TITLE
What about adding a component for VTIMEZONE?

### ISSUE THREAD

**Issue by SimonSimCity** [fruux/sabre-vobject#44]
Hi, all

Just a question to clarify stuff that's not documented ...

I found out quite soon, while trying to port a iCalcreator implementation to this library, that there is no definition for VTIMEZONE creation.

When does a VTIMEZONE component get added to a calendar? Is this based on which VEVENTs I add and the timezone in their start- or endtime, or is it based on something else?

Bye
Simon

**Comment by DominikTo** [comment]
Closing this in favor of #248.
